# Generated by Django 3.1.5 on 2021-05-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=100),
        ),
    ]
