# Generated by Django 3.1.5 on 2021-05-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_totl',
            new_name='shipping_total',
        ),
    ]
